"""Contempo — Universo Presente.

Takes the past generated by Chronica and builds the present.
Deterministic given Chronica — no new randomness.

Instantiates:
- IN12 with H00 state
- Minor Wheel (secondary/tertiary characters by harmonic affinity)
- Event tree (BN1 and future acts)

X + Y converges here as the inevitable attractor.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..core.entity import BaseEntity, Character, MacroFaction, Location
from ..core.lifepack import LifePack, populate_octave_7
from ..core.relation import Relation
from ..core.seed import apply_seed_variation
from ..core.world_state import WorldState


class ContempoError(Exception):
    """Raised when Contempo fails."""


_ENTITY_LOADERS: dict[str, type[BaseEntity]] = {
    "character": Character,
    "macro_faction": MacroFaction,
    "location": Location,
}


def run(ws: WorldState, config: dict) -> WorldState:
    """Execute Contempo layer.

    Args:
        ws: WorldState from Chronica.
        config: Worldpack configuration with paths.

    Returns:
        WorldState with phase='contempo', present state ready for simulation.

    Raises:
        ContempoError: If required data is missing.
    """
    ws = ws.model_copy(deep=True)

    # Load characters (IN12)
    characters_path = config.get("characters_path")
    if characters_path:
        ws = _load_characters(ws, Path(characters_path))

    # Load factions (macro-factions with embedded factions)
    factions_path = config.get("factions_path")
    if factions_path:
        ws = _load_factions(ws, Path(factions_path))

    # Load locations L3+ (districts, buildings, etc.)
    locations_path = config.get("locations_path")
    if locations_path:
        ws = _load_locations_l3_plus(ws, Path(locations_path))

    # Load relations
    relations_path = config.get("relations_path")
    if relations_path:
        ws = _load_relations(ws, Path(relations_path))

    # Load lifepacks
    lifepacks_dir = config.get("lifepacks_dir")
    if lifepacks_dir:
        ws = _load_lifepacks(ws, Path(lifepacks_dir))

    # Build active lists
    ws = _build_active_lists(ws)

    # Apply seed variation (if invariants provided)
    invariants_path = config.get("invariants_path")
    catalogs_data = config.get("catalogs")
    if invariants_path and Path(invariants_path).exists():
        apply_seed_variation(
            ws,
            invariants_path=Path(invariants_path),
            catalogs=catalogs_data,
        )

    ws.phase = "contempo"
    return ws


def _load_json(path: Path) -> list[dict[str, Any]]:
    """Load a JSON file, handling both plain arrays and object wrappers."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(raw, list):
        return raw
    if isinstance(raw, dict):
        for key in ("characters", "relations", "locations", "factions"):
            if key in raw:
                return raw[key]
        return []
    return []


def _load_characters(ws: WorldState, path: Path) -> WorldState:
    """Load character entities."""
    if not path.exists():
        return ws

    for raw in _load_json(path):
        char = Character(**raw)
        ws.entities[char.id] = char

    return ws


def _load_factions(ws: WorldState, path: Path) -> WorldState:
    """Load macro-factions, handling both embedded and split formats."""
    if not path.exists():
        return ws

    raw = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(raw, list):
        # Old flat format: list of MacroFaction dicts with embedded factions
        mfacs = raw
    elif isinstance(raw, dict) and "macro_factions" in raw:
        # New split format: {macro_factions: [...], factions: [...]}
        mfacs = raw["macro_factions"]
        # Group factions by macro_faction_id
        facs_by_mfac: dict[str, list[dict]] = {}
        for f in raw.get("factions", []):
            mfid = f.get("macro_faction_id", "")
            facs_by_mfac.setdefault(mfid, []).append(f)
        # Embed factions into each macro-faction
        result = []
        for mf in mfacs:
            mf_copy = dict(mf)
            mf_copy["factions"] = facs_by_mfac.get(mf_copy["id"], [])
            result.append(mf_copy)
        mfacs = result
    else:
        mfacs = _load_json(path)

    for raw_mf in mfacs:
        mf = MacroFaction(**raw_mf)
        ws.entities[mf.id] = mf

    return ws


def _normalize_location(raw: dict[str, Any]) -> dict[str, Any]:
    """Normalize new-format location fields to match the Location model."""
    d = dict(raw)
    # level → zone_level
    if "level" in d and "zone_level" not in d:
        d["zone_level"] = d.pop("level")
    # parent → parent_location_id
    if "parent" in d and "parent_location_id" not in d:
        d["parent_location_id"] = d.pop("parent")
    # faction_control → controlling_macro_faction_id
    if "faction_control" in d and "controlling_macro_faction_id" not in d:
        d["controlling_macro_faction_id"] = d.pop("faction_control")
    # Ensure entity_type
    if "entity_type" not in d:
        d["entity_type"] = "location"
    # Ensure canon_level
    if "canon_level" not in d:
        d["canon_level"] = "fixed"
    # Ensure name
    if "name" not in d:
        d["name"] = d.get("id", "")
    # Filter to known fields
    known = {
        "id", "entity_type", "name", "tags", "canon_level", "description",
        "tonic", "zone_level", "parent_location_id", "biome_tags",
        "status", "controlling_macro_faction_id", "secondary_macro_faction_ids",
        "tension", "access",
    }
    return {k: v for k, v in d.items() if k in known}


def _load_locations_l3_plus(ws: WorldState, path: Path) -> WorldState:
    """Load locations L3+ (districts, buildings, etc.).

    Skips territory-level locations which are loaded in Theogony.
    """
    if not path.exists():
        return ws

    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, list):
        locations_list = data
    else:
        locations_list = data.get("locations", [])

    for raw in locations_list:
        level = raw.get("level", "")
        # Skip territory-level (loaded in Theogony) and world-level (Genesis)
        if level in ("world", "territory"):
            continue

        # Skip if already exists (from previous layers)
        loc_id = raw["id"]
        if loc_id in ws.entities:
            continue

        normalized = _normalize_location(raw)
        loc = Location(**normalized)
        ws.entities[loc.id] = loc

    return ws


def _load_relations(ws: WorldState, path: Path) -> WorldState:
    """Load relation instances."""
    if not path.exists():
        return ws

    for raw in _load_json(path):
        rel = Relation(**raw)
        ws.relations.append(rel)

    return ws


def _load_lifepacks(ws: WorldState, lifepacks_dir: Path) -> WorldState:
    """Load lifepacks and auto-populate octave 7."""
    if not lifepacks_dir.is_dir():
        return ws

    for lp_path in sorted(lifepacks_dir.glob("*.json")):
        raw = json.loads(lp_path.read_text(encoding="utf-8"))
        lp = LifePack.model_validate(raw)
        char_id = lp.meta.entity_id
        if char_id:
            ws.lifepacks[char_id] = lp

    # Auto-populate octave 7 for each lifepack
    if ws.lifepacks:
        all_chars = [
            (eid, ent.name, ent.note)
            for eid, ent in ws.entities.items()
            if isinstance(ent, Character)
        ]
        for lp in ws.lifepacks.values():
            populate_octave_7(lp, all_chars)

    return ws


def _build_active_lists(ws: WorldState) -> WorldState:
    """Build active macro-faction and location lists."""
    ws.active_macro_faction_ids = [
        eid for eid, e in ws.entities.items()
        if e.entity_type == "macro_faction" and getattr(e, "status", "") != "dissolved"
    ]
    # Add locations not already in active list
    for eid, e in ws.entities.items():
        if e.entity_type == "location" and eid not in ws.active_location_ids:
            ws.active_location_ids.append(eid)

    return ws
